spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 800654329546-mqocdqact8brgnbl68slkc6rcppblc3m.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email